/**
 * Lab Assignment
 * ──────────────
 * Task 1:
 *   An array of N elements is filled with random numbers from 0 to 50.
 *   Even elements are sorted in DESCENDING order using merge sort.
 *   Odd elements remain in their original positions.
 *
 * Task 2:
 *   Measure sorting time for arrays of various sizes.
 */

#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <ctime>
#include <chrono>
#include <vector>
#include <string>
#include <cmath>

using namespace std;
using namespace std::chrono;

// ─── Constants ───────────────────────────────────────────────────────────────

const int RANDOM_MIN = 0;
const int RANDOM_MAX = 50;
const int ELEMENTS_PER_LINE = 20;   // how many numbers to print per line
const int TIMING_REPEATS = 10;   // how many times to repeat each timing measurement

// ─── Array utilities ─────────────────────────────────────────────────────────

void fillArrayWithRandomValues(int* array, int size, int minValue, int maxValue) {
    for (int index = 0; index < size; ++index)
        array[index] = minValue + rand() % (maxValue - minValue + 1);
}

void printArray(const int* array, int size, const string& title) {
    cout << "\n" << title << " (" << size << " elements):\n";
    for (int index = 0; index < size; ++index) {
        cout << setw(4) << array[index];
        if ((index + 1) % ELEMENTS_PER_LINE == 0)
            cout << "\n";
    }
    cout << "\n";
}

void printEvenElements(const int* array, int size, const string& label) {
    cout << label << ": ";
    for (int index = 0; index < size; ++index)
        if (array[index] % 2 == 0)
            cout << array[index] << " ";
    cout << "\n";
}

// ─── Merge sort algorithm ────────────────────────────────────────────────────
//
//                              merge sort was generated by claude ai sonnet 4.6
//
// Sorts the vector in DESCENDING order.
// The merge condition  leftValue >= rightValue  ensures descending order.

void mergeSortedHalves(vector<int>& values, int leftIndex, int middleIndex, int rightIndex) {
    // Copy the left and right halves into temporary vectors
    vector<int> leftHalf(values.begin() + leftIndex,
        values.begin() + middleIndex + 1);
    vector<int> rightHalf(values.begin() + middleIndex + 1,
        values.begin() + rightIndex + 1);

    int leftPos = 0;
    int rightPos = 0;
    int writePos = leftIndex;

    // Compare elements from both halves and write the larger one first
    while (leftPos < (int)leftHalf.size() && rightPos < (int)rightHalf.size()) {
        if (leftHalf[leftPos] >= rightHalf[rightPos])
            values[writePos++] = leftHalf[leftPos++];
        else
            values[writePos++] = rightHalf[rightPos++];
    }

    // Append the remaining elements of the left or right half
    while (leftPos < (int)leftHalf.size())  values[writePos++] = leftHalf[leftPos++];
    while (rightPos < (int)rightHalf.size()) values[writePos++] = rightHalf[rightPos++];
}

void mergeSort(vector<int>& values, int leftIndex, int rightIndex) {
    if (leftIndex >= rightIndex)
        return;

    int middleIndex = leftIndex + (rightIndex - leftIndex) / 2;

    mergeSort(values, leftIndex, middleIndex);
    mergeSort(values, middleIndex + 1, rightIndex);
    mergeSortedHalves(values, leftIndex, middleIndex, rightIndex);
}

// ─── Sort only the even elements of the array ────────────────────────────────
//
// Idea:
//   1. Extract even elements into a separate vector, remembering their positions.
//   2. Sort the vector of even values in descending order.
//   3. Write the sorted values back to the same positions.
//   Odd elements are not touched.

void sortEvenElementsDescending(int* array, int size) {
    vector<int> evenValues;
    vector<int> evenPositions;

    for (int index = 0; index < size; ++index) {
        if (array[index] % 2 == 0) {
            evenValues.push_back(array[index]);
            evenPositions.push_back(index);
        }
    }

    if (evenValues.empty())
        return;

    mergeSort(evenValues, 0, (int)evenValues.size() - 1);

    for (int i = 0; i < (int)evenPositions.size(); ++i)
        array[evenPositions[i]] = evenValues[i];
}

// ─── Task 1: demonstrate sorting on an array of the given size ───────────────

void demonstrateSorting(int arraySize) {
    cout << "\n --------------------------------------------------------";
    cout << "\n|                TASK 1: Merge Sort                      |";
    cout << "\n --------------------------------------------------------\n";
    cout << "Array size N = " << arraySize << "\n";

    int* array = new int[arraySize];
    fillArrayWithRandomValues(array, arraySize, RANDOM_MIN, RANDOM_MAX);

    printArray(array, arraySize, "Original array");
    printEvenElements(array, arraySize, "Even elements BEFORE sorting");

    sortEvenElementsDescending(array, arraySize);

    printArray(array, arraySize, "Sorted array (even elements descending)");
    printEvenElements(array, arraySize, "Even elements AFTER sorting");

    delete[] array;
}

// ─── Task 2: measure sorting time ────────────────────────────────────────────

// Runs sorting TIMING_REPEATS times and returns the average time in microseconds
double measureAverageSortTimeMicroseconds(int arraySize) {
    int* array = new int[arraySize];
    double totalTimeMicroseconds = 0.0;

    for (int attempt = 0; attempt < TIMING_REPEATS; ++attempt) {
        fillArrayWithRandomValues(array, arraySize, RANDOM_MIN, RANDOM_MAX);

        auto startTime = high_resolution_clock::now();
        sortEvenElementsDescending(array, arraySize);
        auto endTime = high_resolution_clock::now();

        totalTimeMicroseconds += duration_cast<nanoseconds>(endTime - startTime).count() / 1000.0;
    }

    delete[] array;
    return totalTimeMicroseconds / TIMING_REPEATS;
}

void measureAndPrintTimings() {
    cout << "\n --------------------------------------------------------";
    cout << "\n|           TASK 2: Sorting time measurement             |";
    cout << "\n --------------------------------------------------------\n";

    vector<int> testSizes = { 100, 500, 1000, 5000, 10000, 50000, 100000 };

    cout << "\n" << string(52, '-') << "\n";
    cout << setw(10) << "N"
        << setw(22) << "Average time (us)"
        << setw(20) << "Time growth"
        << "\n";
    cout << string(52, '-') << "\n";

    double previousTime = 0.0;

    for (int currentSize : testSizes) {
        double averageTime = measureAverageSortTimeMicroseconds(currentSize);

        cout << setw(10) << currentSize
            << setw(18) << fixed << setprecision(2) << averageTime << " us";

        if (previousTime > 0.0)
            cout << setw(12) << fixed << setprecision(2)
            << (averageTime / previousTime) << "x";
        else
            cout << setw(12) << "—";

        cout << "\n";
        previousTime = averageTime;
    }

    cout << string(52, '-') << "\n";

    cout << R"(
Results explanation:
────────────────────
1. Merge sort operates only on even elements (~N/2 elements),
   so the actual complexity is: O((N/2) * log2(N/2)) ~ O(N * log N).

2. The "Time growth" column shows how many times the time increased
   compared to the previous array size. When N doubles, the theoretical
   expected growth is ~2.1x, which confirms the log-linear complexity.

3. For small N (100-500) the overhead of function calls and temporary
   vector allocations is noticeable, so the growth factor may deviate
   from the theoretical value.

4. Merge sort always runs in O(N * log N) -- even in the worst case
   (already sorted or reverse-sorted input), unlike quicksort which
   degrades to O(N^2).
)";
}

// ─── Read array size from keyboard ───────────────────────────────────────────

int readArraySizeFromKeyboard() {
    int size = 0;
    cout << "Enter array size N (recommended: 40): ";
    while (!(cin >> size) || size <= 0) {
        cin.clear();
        cin.ignore(1000, '\n');
        cout << "Invalid input. Please enter a positive integer: ";
    }
    return size;
}

// ─── main ─────────────────────────────────────────────────────────────────────

int main() {
    srand(static_cast<unsigned>(time(nullptr)));

    int arraySize = readArraySizeFromKeyboard();
    demonstrateSorting(arraySize);
    measureAndPrintTimings();

    return 0;
}